asn1crypto==0.24.0
awscli==1.16.183
botocore==1.12.173
cachetools==3.1.1
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
colorama==0.3.9
conda==4.6.14
cryptography==2.7
dialogflow==0.6.0
dlib==19.17.0
docutils==0.14
google-api-core==1.14.2
google-auth==1.6.3
google-cloud==0.34.0
google-cloud-pubsub==1.0.1
googleapis-common-protos==1.6.0
grpc-google-iam-v1==0.12.3
grpcio==1.24.0
idna==2.7
imutils==0.5.2
jmespath==0.9.4
numpy==1.16.4
opencv-python==4.1.0.25
protobuf==3.9.2
pyasn1==0.4.5
pyasn1-modules==0.2.6
pycosat==0.6.3
pycparser==2.18
pymongo==3.7.2
pyOpenSSL==18.0.0
PySocks==1.6.8
python-dateutil==2.8.0
pytz==2019.2
PyYAML==5.1
requests==2.19.1
rsa==3.4.2
ruamel-yaml==0.15.46
s3transfer==0.2.1
six==1.11.0
urllib3==1.23
virtualenv==16.7.4
yapf==0.27.0
